# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(db_column='descricao', max_length=255)),
                ('user_creation', models.IntegerField(db_column='user_criacao')),
                ('data_creation', models.DateField(db_column='data_criacao')),
                ('state', models.IntegerField(db_column='estado')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('code_us', models.CharField(max_length=255)),
                ('sorting_us', models.CharField(db_column='classificacao_us', max_length=255)),
                ('level_us', models.CharField(db_column='nivel_us', max_length=255)),
                ('ugly_us', models.CharField(db_column='fea_us', max_length=255)),
                ('province_capital_dist', models.IntegerField(null=True)),
                ('device_serial', models.CharField(max_length=255)),
                ('sim_number', models.CharField(db_column='sim_numb', max_length=255, unique=True)),
                ('sim_serial', models.CharField(max_length=255, unique=True)),
                ('device_number', models.CharField(db_column='device_numb', max_length=255)),
                ('state', models.IntegerField(db_column='estado')),
                ('person_contact_opt', models.CharField(db_column='pessoa_contacto_opt', max_length=255)),
                ('phone_contact_opt', models.CharField(db_column='telefone_contacto_opt', max_length=255)),
                ('sim_number_opt', models.CharField(db_column='sim_numb_opt', max_length=255, unique=True)),
                ('sim_serial_opt', models.CharField(max_length=255, unique=True)),
                ('mac_number', models.CharField(db_column='mac_numb', max_length=255)),
                ('device_serial_opt', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsd.District')),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(db_column='descricao', max_length=255)),
                ('data_creation', models.CharField(db_column='data_criacao', max_length=255, null=True)),
                ('user_creation', models.IntegerField(db_column='user_criacao')),
                ('state', models.IntegerField(db_column='estado')),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsd.Province'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsd.Province'),
        ),
    ]
