# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='data_creation',
            field=models.DateField(db_column='data_criacao', null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.CharField(db_column='descricao', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.IntegerField(db_column='estado', null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='user_creation',
            field=models.IntegerField(db_column='user_criacao', null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='data_creation',
            field=models.DateField(db_column='data_criacao', null=True),
        ),
    ]
