# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BesVersionCore',
        ),
        migrations.RemoveField(
            model_name='district',
            name='province',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='district',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='province',
        ),
        migrations.DeleteModel(
            name='SenderFromVersionCore',
        ),
        migrations.AlterField(
            model_name='datasetelement',
            name='data_set_id',
            field=models.CharField(default='0f70951d-0d80-41c4-ab50-71f18758c27d', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetelement',
            name='uid',
            field=models.CharField(default='9a38e100-30b5-48dc-a065-e9ef7b6c42e8', max_length=225),
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
