# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='besmiddlewarecore',
            old_name='note_malaria',
            new_name='note_malaria_clinic',
        ),
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='note_malaria_confirmed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
