# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0003_merge_20160830_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besmiddlewarecore',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sendermiddlewarecore',
            name='id',
        ),
        migrations.AlterField(
            model_name='besmiddlewarecore',
            name='uri',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendermiddlewarecore',
            name='uri',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
