# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0003_auto_20160926_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besmiddlewarecore',
            name='cases_malaria_5',
        ),
    ]
