# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0004_auto_20160829_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetelement',
            name='data_set_id',
            field=models.CharField(default='65d602d5-e3ee-4d24-8761-4468d0c57e8b', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasetelement',
            name='uid',
            field=models.CharField(default='b8eefb48-9318-4e66-95f9-458a7d4ba17f', max_length=225),
        ),
        migrations.AlterModelTable(
            name='senderfromversioncore',
            table='REMETENTE_MIDDLEWARE_CORE',
        ),
    ]
