# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0004_auto_20160830_0526'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='besmiddlewarecore',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sendermiddlewarecore',
            table=None,
        ),
    ]
