# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0004_remove_besmiddlewarecore_cases_malaria_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besmiddlewarecore',
            name='middleware_created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='besmiddlewarecore',
            name='middleware_updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
