# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0005_auto_20160830_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='orgUnitAttr',
            new_name='org_unit_attr',
        ),
        migrations.RenameField(
            model_name='attribute',
            old_name='valueType',
            new_name='value_type',
        ),
    ]
