# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0006_auto_20160926_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='deaths_malaria_confirmed_0_4',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
