# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0007_besmiddlewarecore_deaths_malaria_confirmed_0_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCOCRelation',
            fields=[
                ('disease_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('disease_name', models.CharField(default='', max_length=255)),
                ('disease_uid', models.CharField(default='', max_length=255)),
                ('cases_coc_id', models.CharField(default='', max_length=255)),
                ('deaths_coc_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
