# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0008_historicalcocrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcocrelation',
            name='cases_coc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_coc_id', to='dsd.COCRelation'),
        ),
        migrations.AlterField(
            model_name='historicalcocrelation',
            name='deaths_coc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths_coc_id', to='dsd.COCRelation'),
        ),
    ]
