# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0008_auto_20160831_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='org_unit_attr',
        ),
        migrations.AddField(
            model_name='attribute',
            name='attr_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
