# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0009_auto_20160901_0237'),
        ('dsd', '0010_auto_20160901_0249'),
    ]

    operations = [
    ]
