# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0011_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='province_capital_dist',
        ),
        migrations.AddField(
            model_name='facility',
            name='contact_person',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='phone_contact',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
