# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0011_merge_20160901_0811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table=None,
        ),
    ]
