# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0012_auto_20170222_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sim_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sim_number_opt',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sim_serial',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sim_serial_opt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
