# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0012_auto_20160902_0137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table=None,
        ),
        migrations.AlterModelTable(
            name='facility',
            table=None,
        ),
        migrations.AlterModelTable(
            name='province',
            table=None,
        ),
    ]
