# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0014_districtpopulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='middleware_district_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='middleware_facility_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='middleware_province_id',
            field=models.IntegerField(null=True),
        ),
    ]
