# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0015_auto_20170307_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='besmiddlewarecore',
            name='middleware_stale',
            field=models.IntegerField(null=True),
        ),
    ]
