# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0016_categorycombination'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='category_combo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dsd.CategoryCombination'),
        ),
    ]
