# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0017_element_category_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
