# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsd', '0018_auto_20160902_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='COCRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_bes', models.CharField(default='', max_length=255)),
                ('element_id', models.CharField(default='', max_length=255)),
                ('cc_id', models.CharField(default='', max_length=255)),
                ('name_of_coc', models.CharField(default='', max_length=255)),
                ('coc_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
